#FROM alpine:3.14

#RUN apk add nodejs-npm build-base musl-dev

FROM node:14-alpine3.12

# Create app directory
WORKDIR /sla_monitor

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY sources/package*.json ./

#RUN npm install
RUN npm install --save
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY sources/ .

EXPOSE 8080

#CMD ["/usr/bin/npm", "run", "start"]
#CMD ["node", "index.js"]
CMD ["node", "index.js"]
