#FROM sconecuratedimages/kubernetes:python-3.7.3-alpine3.10-scone4.2
FROM alpine:3.15

RUN apk add python3 py3-pip build-base musl-dev python3-dev
#RUN pip install fastapi uvicorn kafka-python minio numpy pandas

WORKDIR /tee-manager

RUN pip install --upgrade pip
COPY ./sources/Flask/requirements.txt requirements.txt
RUN pip install -r requirements.txt

EXPOSE 8080
COPY ./sources/Flask .
CMD [ "python3", "app.py" ]
